### ISSUE TITLE
Kernel panic after running kvm-qemu.sh

### ISSUE THREAD

**Issue by hawk4n6** [doomedraven/Tools#102]
Current script version (81d18a5c43f91c10b6c444983474a37bd1b2349a) causes an real strange error:

During execution of kvm-qemu.sh something failed into the system. No program can be found anymore, no further action is possible, no programs can be started. I can't do anything except Reset or Power-Off the computer. When rebooting a Kernel Panic occurs. Neither rescue mode nor an older Kernel version can be started.

This happens twice at two different computers in an fresh Ubuntu 20.04 amd64 LTS installation with all available updates installed. I used the current kvm-qemu.sh script from GitHub.

This seems to happen during function **install_apparmor,** which was added with the last commit. I don't have any hint what went wrong. I'll repeat the installation with stdout/stderr logging.

**Comment by doomedraven** [comment]
Hello, that is probably due to checkinstall, see https://github.com/doomedraven/Tools/issues/88
I had the same issue this weekend, but that was the first time that it happens to me, so soon I will push a version without checkinstall

**Comment by doomedraven** [comment]
thanks for find what exactly generates this problem, this part of code was working just fine as we tested that you can see conversation here https://github.com/doomedraven/Tools/issues/100, so is checkinstall as i though breaks the OS due to error, im gonna disable that right now and once i will have a bit more time to test this i will push a `checkinstall` free version, the idea is to use something like in that PR that i show you

```
mkdir -p /tmp/apparmor-"$APPARMOR_VERSION"_builded/DEBIAN
    echo -e "Package: apparmor-parser\nVersion: $APPARMOR_VERSION\nArchitecture: $ARCH\nMaintainer: $MAINTAINER\nDescription: Custom antivm qemu" > /tmp/apparmor-"$APPARMOR_VERSION"_builded/DEBIAN/control
    make -j"$(nproc)" install DESTDIR=/tmp/apparmor-"$APPARMOR_VERSION"_builded
    dpkg-deb --build --root-owner-group /tmp/apparmor-"$APPARMOR_VERSION"_builded
    apt -y -o Dpkg::Options::="--force-overwrite" install /tmp/apparmor-"$APPARMOR_VERSION"_builded.deb
```

im gonna disable that func right now in code

**Comment by doomedraven** [comment]
if you want to test i have tested, no issues anymore, no more love to checkinstall from me  https://github.com/doomedraven/Tools/blob/master/Virtualization/kvm-qemu.sh

**Comment by hawk4n6** [comment]
Hello,
yes, fixed, script is running again without errors. Thanks for fixing!

**Comment by doomedraven** [comment]
thank you for feedback, let me know if you find any other issue, glad that we finally removed checkinstall
