### ISSUE TITLE
libvirtd failed, sysctl.conf settings, dnsmasq failed

### ISSUE THREAD

**Issue by hawk4n6** [doomedraven/Tools#103]
Hello,

installation with the updated kvm-qemu.sh script doesn't show any error, neither cape2.sh. After rebooting some modules doesn't work:

**libvirtd not started**, reason:
```
aa-complain /etc/apparmor.d/usr.sbin.libvirtd
ERROR: AppArmor analysis error for /etc/apparmor.d/usr.sbin.libvirtd in /etc/apparmor.d/usr.sbin.libvirtd in Line 29: Unknown capability bpf.
```

I can't find anything related to apparmor + bpf. Setting security_driver = "none" in /etc/libvirt/qemu.conf does fix this error, but that doesn't seem to be the correct solution.

Wrong target - this should go to sysctl.conf:
```
CRON[12638]: pam_limits(cron:session): invalid line 'net.core.default_qdisc=fq' - skipped
CRON[12638]: pam_limits(cron:session): invalid line 'net.ipv4.tcp_congestion_control=bbr' - skipped
```
```    
if ! grep -q -E '^net.core.default_qdisc=fq' /etc/security/limits.conf; then
        echo "net.core.default_qdisc=fq" >> /etc/security/limits.conf
        echo "net.ipv4.tcp_congestion_control=bbr" >> /etc/security/limits.conf
    fi
```

My fresh Ubuntu 20.04 installation uses **systemd-resolved**, so port 53 is already in use. Installation of dnsmasq doesn't remove nor disable systemd-resolved, dnsmasq won't start. To fix:
```
systemctl stop systemd-resolved
systemctl disable systemd-resolved
rm /etc/resolv.conf 
echo nameserver 8.8.8.8 | sudo tee /etc/resolv.conf
systemctl restart dnsmasq
```

**Comment by doomedraven** [comment]
hello, 
1. about your problem with `bpf` sound like for some reason new apparmor_parsers wasn't installed - https://github.com/doomedraven/Tools/issues/100
2. thanks about limits.conf 
3. im not sure what installs dnsmasq, but you don't need to care about that

**Comment by hawk4n6** [comment]
Hello,

after reinstalling apparmor_parser by using the code inside function install_apparmor libvirtd.service could be started. But I need to install the package manually with "dkpg -I --force-overwrite" because the apt command doesn't install the package.

dnsmasq is installed from kvm-qemu.sh line 473.

**Comment by doomedraven** [comment]
thanks will change comamnd, about dnsmasq, i see, but that is dependency of libvirt, but i personally never use dnsmasq

**Comment by hawk4n6** [comment]
service dnsmasq failed to start so I tried to solve this problem. Don't realized this is an dependency from libvirt.

I'll try a new, fresh installation of everthing and then check if this service can be disabled to prevent further failure messages fron dnsmasq. Anyway, kvm-qemu.sh is a really very usefull but complex script, thanks for this!

**Comment by doomedraven** [comment]
i have a tip for you, that I spot, i was wondering why dns wasn't working when i was using dhcp to set VMs IP address, and DNS wasn't working so thats it, i will have to update it to include your suggestion for fix how to enable that https://www.doomedraven.com/2016/05/kvm.html#assign-static-guest-ip-addresses-using-dhcp-on-the-virtual-machine

glad that you have found it useful, the biggest problem is OS updates + software updates, is super hard to balance to not break something, is why i stay with ubuntu LTS only, if you have any suggestion/bug/feature req let me know

**Comment by hawk4n6** [comment]
Installation of apparmor doesn't really work at all. Don't know why, but that's the result from a new, fresh installation and running kvm-qemu.sh:

kvm-qemu.sh does build apparmor-2.13.6_builded.deb with a file size of 104 kB only. No binary included. Compiling reports an error, bison is not found:
```
make[1]: Entering directory '/tmp/libvirt-python-7.7.0/apparmor-2.13.6/parser'
g++ -g -O2 -pipe  -Wall -Wsign-compare -Wmissing-field-initializers -Wformat-security -Wunused-parameter -std=gnu++0x -D_GNU_SOURCE  -DPACKAGE=\"apparmor-parser\" -DLOCALEDIR=\"/usr/share/locale\" -DSUBDOMAIN_CONFDIR=\"/etc/apparmor\"  -c -o parser_common.o parser_common.c
g++ -g -O2 -pipe  -Wall -Wsign-compare -Wmissing-field-initializers -Wformat-security -Wunused-parameter -std=gnu++0x -D_GNU_SOURCE  -DPACKAGE=\"apparmor-parser\" -DLOCALEDIR=\"/usr/share/locale\" -DSUBDOMAIN_CONFDIR=\"/etc/apparmor\"  -c -o parser_include.o parser_include.c
g++ -g -O2 -pipe  -Wall -Wsign-compare -Wmissing-field-initializers -Wformat-security -Wunused-parameter -std=gnu++0x -D_GNU_SOURCE  -DPACKAGE=\"apparmor-parser\" -DLOCALEDIR=\"/usr/share/locale\" -DSUBDOMAIN_CONFDIR=\"/etc/apparmor\"  -c -o parser_interface.o parser_interface.c
bison -d -o parser_yacc.c parser_yacc.y
make[1]: bison: Command not found
make[1]: *** [Makefile:200: parser_yacc.h] Error 127
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/tmp/libvirt-python-7.7.0/apparmor-2.13.6/parser'
make: *** [Makefile:378: install] Error 2
dpkg-deb: Paket »apparmor-parser« wird in »/tmp/apparmor-2.13.6_builded.deb« gebaut.
```

I copied the code block from **function install_apparmor** to a new bash script and run only this script. This time it's working, no error and the created deb paket as a file size of 2 MB, inkluding binary.

Thanks for the IP hint. I'm preparing a script which does set some configurations and parameters, download and run kvm-qemu.sh und cape2.sh and do some further steps.

**Comment by doomedraven** [comment]
so you have the same issue as before with kernel panic, note bison missed, how do you run the script? as it installed in another block, but i think i will need to install it here too

**Comment by hawk4n6** [comment]
No kernel panic. Compiling apparmor failed because bison is not found, so the newer version of apparmor_parser is not installed. I can't see any reason for this, and outside kvm-qemu.sh the same code is running perfect. Currently I can't see any further problems in kvm-qemu.sh, but I need more time to check everything.

My script is executed as root, installs some additional packages, edit some configurations (custom DNS, libvirt network config, set parameter in cape2.sh, configure cape config files, ...), download kvm-qemu.sh via wget, chmod the script and then run it with parameter "all cape". It's not ready yet, and I've the same update problems as you mentioned.

**Comment by doomedraven** [comment]
Weird with all it should install, i have added bison to apparmor parser
function just in case

**Comment by hawk4n6** [comment]
I did a new fresh install. Unfortunately also **flex** is not found. After installing flex first the following installation of apparmor is successfull. With bison and flex added kvm-qemu.sh seems to run successfull, I can't see any further problems yet.

**Comment by doomedraven** [comment]
Thanks, i will add that once i will be with pc
