### ISSUE TITLE
KVM snapshot failed, qxl error

### ISSUE THREAD

**Issue by hawk4n6** [doomedraven/Tools#105]
kvm-qemu.sh was executed successfully, no error reported. After reboot I created a new VM (Windows 10). Creating an snapshot failed with the following error:

```
operation failed: Failed to take snapshot: pre-save failed: qxl
Error: Error while writing VM state: Unknown error -1

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 72, in cb_wrapper
    callback(asyncjob, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/details/snapshots.py", line 237, in _do_create_snapshot
    self.vm.create_snapshot(xml)
  File "/usr/share/virt-manager/virtManager/object/domain.py", line 1124, in create_snapshot
    self._backend.snapshotCreateXML(xml, flags)
  File "/usr/local/lib/python3.8/dist-packages/libvirt.py", line 3063, in snapshotCreateXML
    raise libvirtError('virDomainSnapshotCreateXML() failed')
libvirt.libvirtError: operation failed: Failed to take snapshot: pre-save failed: qxl
Error: Error while writing VM state: Unknown error -1
```

Google said this is caused by spice server? I can't find a new Ubuntu package then 0.14.2-4ubuntu3.1 (libspice-server1). An downgrade to qemu 6.0.0 should fix the problem? (from Google)

Spice packages were installed from Ubuntu 20.04 repositories by kvm-qemu.sh.

qemu_version=6.1.0
libvirt_version=7.7.0
virt-manager=3.2.0

**Comment by doomedraven** [comment]
Just dont use qxl as video driver nd thats all

**Comment by hawk4n6** [comment]
Argh! Sometimes the solution is too simple. Of course, thanks.

**Comment by doomedraven** [comment]
you are welcome, maybe in 6.2 they will fix it, is the fun of the edging software :)
