### ISSUE TITLE
Error with compiling

### ISSUE THREAD

**Issue by DarkMinerULTRA** [doomedraven/Tools#109]
it said that glib-2.56 gthread-2.0 is required to compile QEMU. What is that and how do I install it?
The full log:

$ ./configure
Using './build' as the directory for build output
Disabling PIE due to missing toolchain support

ERROR: glib-2.56 gthread-2.0 is required to compile QEMU

My OS is MacOS High Sierra 10.13.6, and on a late-2010 Macbook Air.

**Comment by doomedraven** [comment]
that won't work for MacOS, it only for linux, in past i tried to adapt that for Darwin, but meh

**Comment by DarkMinerULTRA** [comment]
oh :(
