### ISSUE TITLE
kvm-qemu.sh does not seem to work on Ubuntu 20.04 LTS fresh install

### ISSUE THREAD

**Issue by sgarringer** [doomedraven/Tools#112]
# Expected Behavior

Running kvm-qemu.sh as root should compile qemu and install on Ubuntu 20 LTS

# Current Behavior

Running kvm-qemu.sh as root does not compile on Ubuntu 20

# Failure Information (for bugs)

[+] Patching QEMU clues
[+] Starting compile it
Using './build' as the directory for build output
ERROR: unknown option --enable-libxml2
Try '/tmp/qemu-7.0.0/configure --help' for more information
[-] Compilling failed

## Steps to Reproduce

sudo ./kvm-qemu.sh all

| Question         | Answer
|------------------|--------------------
| OS version       | Ubuntu 20.04
| Software version | Latest from git

**Comment by doomedraven** [comment]
get a fresh version, i was testing that win ubuntu 22, and removed that for mac instead of linux xD

**Comment by sgarringer** [comment]
Bad timing on my part, I have refreshed and running again.

**Comment by doomedraven** [comment]
nah, that my bad that i thought that i removed it in both places, let me know if you spot any other issue, on ubuntu 22 everything works just fine less virt-manager

**Comment by sgarringer** [comment]
I'll close this for now, I'm running through the cape install for the first time on this box
