### ISSUE TITLE
Receiving error related to Rooter when I run "python3 cuckoo.py" for CapeV2 sandbox

### ISSUE THREAD

**Issue by dhruvpatel56** [doomedraven/Tools#124]
## This is opensource and you getting __free__ support so be friendly! 
* Wants to say thanks -> [buy me a beer](https://opencollective.com/virustotalapi)

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [Yes ] I checked to make sure that this issue has not already been filed
- [ Yes] I'm reporting the issue to the correct repository (for multi-repository projects)
- [ Yes] I read my log of instalation, all issues will be closed if you don't do your part of work
- [ Yes] I understand that reporting issue related to any instalation script without instalation log is useless and will be closed

# Expected Behavior

Cuckoo.py file should be running just fine.

# Current Behavior

What is the current behavior?
I am getting below error:
![image](https://user-images.githubusercontent.com/50963903/181372174-1d90c08b-6277-4852-be62-7ff1b8fe3042.png)

When I checked the cuckoo.log file:
![image](https://user-images.githubusercontent.com/50963903/181372228-16c4df28-1539-4cfa-9211-fc6eae4c979e.png)

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

**Comment by doomedraven** [comment]
Hello this is wrong repo for reporting this.

You should run it as cape user not like your normal user
