### ISSUE TITLE
Receiving not enough free disk space error when running "python3 cuckoo.py" for CAPEV2 sandbox.

### ISSUE THREAD

**Issue by dhruvpatel56** [doomedraven/Tools#125]
## This is opensource and you getting __free__ support so be friendly! 
* Wants to say thanks -> [buy me a beer](https://opencollective.com/virustotalapi)

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ Yes] I checked to make sure that this issue has not already been filed
- [ Yes] I'm reporting the issue to the correct repository (for multi-repository projects)
- [ Yes] I read my log of instalation, all issues will be closed if you don't do your part of work
- [ Yes] I understand that reporting issue related to any instalation script without instalation log is useless and will be closed

# Expected Behavior

Please describe the behavior you are expecting
Cuckoo.py should run just fine.

# Current Behavior

What is the current behavior?
When I run "python3 cuckoo.py", I am getting below error:
![image](https://user-images.githubusercontent.com/50963903/181373538-cc0339c7-b834-473a-af7d-154a1cf3dee3.png)

I have checked the cuckoo.log which look like below:
![image](https://user-images.githubusercontent.com/50963903/181373644-4304e78d-6753-41d5-b6b9-708d651eeba8.png)

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

**Comment by doomedraven** [comment]
Responded in previos issue
