### ISSUE TITLE
seabios ram and information issue 

### ISSUE THREAD

**Issue by AndreyRz** [doomedraven/Tools#132]
Hi, I used your script to configure seabios, but after that the ability to change the amount of RAM through libvirt disappeared, the system always uses only 2GB of RAM and the entered bios data about the manufacturer and other things from libvirt are also not used.

**Comment by doomedraven** [comment]
2gb of ram is due that it uses bios from apt package which mess with manyvdifferent package

**Comment by AndreyRz** [comment]
Is it possible to fix it somehow? I was installing it on a clean system 22.04.1 lts

**Comment by doomedraven** [comment]
Wrll there is few things

1. If yoyr setup is for malware analysis you broke it somehow installing lubs from apt somehow. I dont have details as ypu didnt provide any details, you can use dpkt to inspect your system
2. It could be that seobios failed and wasnt replaced, but once again no details from you, you can rerun script with seabios command

**Comment by AndreyRz** [comment]
sudo ./kvm-qemu.sh Replace_seabios /usr/share/qemu
Executed without errors
But ./kvm-qemu.sh SeaBios give me so warnings due to the process:

[screen.log](https://github.com/doomedraven/Tools/files/10774822/screen.log)

**Comment by doomedraven** [comment]
warnings are fine.

```
'out/bios.bin' -> '/usr/share/qemu/bios.bin'
'out/bios.bin' -> '/usr/share/qemu/bios-256k.bin'
```

what are hashes of those 2 files? did you edit xml of your vm to force using those bios files?

**Comment by doomedraven** [comment]
https://www.doomedraven.com/2016/#modifying-kvm-qemu-kvm-settings-for-malware-analysis

**Comment by AndreyRz** [comment]
aaead639905cc532e0df8c62a011faec8beed26f for both files, I edit  xml with 
<domain xmlns:qemu="http://libvirt.org/schemas/domain/qemu/1.0" type="kvm">
qemu:commandline>
    <qemu:arg value='-cpu'/>
    <qemu:arg value='host,-hypervisor,kvm=off'/>
    <qemu:arg value='-L'/>
    <qemu:arg value='/usr/share/qemu/bios.bin'/>
  </qemu:commandline>
and add  <sysinfo type='smbios'> tables

**Comment by doomedraven** [comment]
now run vm and if you can't more ram assigned, search qemu in `ps` to see whole command line. check my old post maybe they broke seobios again https://www.reddit.com/r/qemu_kvm/comments/phsrw8/cant_use_more_than_3gb_ram_on_x64_win10/

**Comment by AndreyRz** [comment]
I've already watched your post, unfortunately I have a windows 10 guest system

**Comment by doomedraven** [comment]
well then it just uses uefi instead of bios and it has default limitations. the person for who i did that investigation is using win10 too, you can try to switch from uefi to bios to try if that is the case

**Comment by AndreyRz** [comment]
When I turn on the virtual machine, the seabios window is displayed. When creating, the bios parameter was also selected.

**Comment by doomedraven** [comment]
what is the build of your seabios that you see on splash?

**Comment by AndreyRz** [comment]
version rel-1.16.1.-2-gea1b7a0-dirty-20230218_201052

**Comment by doomedraven** [comment]
im on 1.14, i would need to check latest version, if you don't want to investigate what is wrong there try to just build with `Working - re1-14.0-26-g54002e8-dirty-2021-0829072634`

**Comment by AndreyRz** [comment]
Ok, i try to use https://github.com/coreboot/seabios/releases/tag/rel-1.14.0 and nothing changed, but I noticed something, comand sed -i 's/CONFIG_XEN=y/CONFIG_XEN=n/g' .config don't work in script, there is error said that no file to apply and if use 
# Windows 10(latest rev.) is uninstallable without ACPI_DSDT
# sed -i 's/CONFIG_ACPI_DSDT=y/CONFIG_ACPI_DSDT=n/g' .config  
windows 2h22 blue screen after startup with acpi error

**Comment by AndreyRz** [comment]
I forgot to write that if you put a clean seabios without corrections to hide it correctly sees the RAM

**Comment by doomedraven** [comment]
Interesting. Thanks

**Comment by doomedraven** [comment]
ok so i just did the tests on my side it works as expected, i guess you have problem with some string replacement for antivm

**Comment by ClaudioWayne** [comment]
Hi,

if you mean the problem regarding to allocate more then 2GB; can you try to build seabios without modifing src/fw/paravirt.c and let me know if it has any effect?
->Line 765  #src/fw/paravirt.c
If I remember correctly, I had the same problem and when I skipped this line, I was able to allocate more than 2 Gb.
I might be wrong, but it's worth a try

**Comment by AndreyRz** [comment]
This made it possible to get 8GB of memory, but again information about timings, the processor multiplier and some other information in cpu-z disappeared, but at the same time information about smbios registered in the libvirt config began to be displayed normally.

**Comment by doomedraven** [comment]
Any that fails, it should be in log

**Comment by AndreyRz** [comment]
Where can I found these logs?

**Comment by doomedraven** [comment]
Terminal output or log if you run as -h says

**Comment by AndreyRz** [comment]
[screen.log](https://github.com/doomedraven/Tools/files/10827961/screen.log)
With ->Line 765 #src/fw/paravirt.c the logs are actually similar, as well as several warnings and a notification that everything is done without errors
