### ISSUE TITLE
QEMU/KVM not connected

### ISSUE THREAD

**Issue by proywm** [doomedraven/Tools#16]
I have installed QEMU and libvirt with kvm-qemu.sh with sudo ./kvm-qemu.sh ALL.
However, when I open virt-manager it says "QEMU/KVM not connected".

libvirtd service is running
$service libvirtd status

● libvirtd.service - Virtualization daemon
   Loaded: loaded (/usr/lib/systemd/system/libvirtd.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2019-07-19 11:08:15 CDT; 5min ago
     Docs: man:libvirtd(8)
           https://libvirt.org
 Main PID: 1083 (libvirtd)
    Tasks: 19 (limit: 32768)
   CGroup: /system.slice/libvirtd.service
           ├─1083 /usr/sbin/libvirtd
           ├─1398 /usr/sbin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/default.conf --leasefile-ro --dhcp-script=/usr/libexec/libvirt_leaseshelper
           └─1399 /usr/sbin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/default.conf --leasefile-ro --dhcp-script=/usr/libexec/libvirt_leaseshelper

What possibly be the issue?

**Comment by doomedraven** [comment]
Hey

so one thing `usermod -G libvirt -a YOUR_USERNAME`, reboot your machine or logout and login
then try `sudo libvirt` if that still doesn't work, you will get more logging on the issue, and post it

**Comment by doomedraven** [comment]
@proywm  any update on this?

**Comment by doomedraven** [comment]
closed as never responded
