### ISSUE TITLE
seabios compilation error

### ISSUE THREAD

**Issue by SangpilKim** [doomedraven/Tools#17]
Hi, 
I'm seeing the following error while executing kvm-qemu.sh script in ubuntu 18.04.2. This error happens on executing seabios_func. I guess <WOOT> makes the problem.
Please let me know how to fix the problem.

out/src/fw/ssdt-misc.dsl.i     65:             Name(_HID, "<WOOT>")
Error    6002 -            String must be entirely alphanumeric ^  (<WOOT>)

out/src/fw/ssdt-misc.dsl.i     82:             Method(RDPT, 0, NotSerialized) {
Warning  4089 -                Object is not referenced ^ 

out/src/fw/ssdt-misc.dsl.i     86:             Method(WRPT, 1, NotSerialized) {
Warning  4089 -                Object is not referenced ^ 

ASL Input:     out/src/fw/ssdt-misc.dsl.i - 102 lines, 2563 bytes, 35 keywords
Listing File:  out/src/fw/ssdt-misc.lst - 10546 bytes
Hex Dump:      out/src/fw/ssdt-misc.hex - 4024 bytes

Compilation complete. 1 Errors, 8 Warnings, 0 Remarks, 2 Optimizations
Makefile:254: recipe for target 'src/fw/ssdt-misc.hex' failed
make: *** [src/fw/ssdt-misc.hex] Error 255
make: *** Waiting for unfinished jobs....
[-] Bios compilation failed

**Comment by doomedraven** [comment]
hm i can't reproduce that 

```
Version: rel-1.12.0-32-g30f1e41
Fixed space: 0xe05b-0x10000  total: 8101  slack: 11  Percent slack: 0.1%
16bit size:           37920
32bit segmented size: 2194
32bit flat size:      38702
32bit flat init size: 81216
Lowmem size:          2240
f-segment var size:   1248
  Linking out/rom16.o
  Linking out/rom32seg.o
  Stripping out/rom32seg.strip.o
  Stripping out/rom16.strip.o
  Linking out/rom.o
  Prepping out/bios.bin.prep
Total size: 169120  Fixed: 80064  Free: 93024 (used 64.5% of 256KiB rom)
  Creating out/bios.bin
```

did you replace <WOOT>?

**Comment by SangpilKim** [comment]
Thank you for the fast response.

No, I just ran kvm-qemu.sh as is.

seabios_func() runs seabios compilation (make -j"$(nproc)") twice as below.
The problem happens in the second seabios compilation. No error is found in
the first compilation returns success.

function seabios_func() {
    cd /tmp || return
    fail=0
    echo '[+] Installing SeaBios dependencies'
    apt-get install git iasl -y
    if [ -d seabios ]; then
        rm -r seabios
    fi
    if git clone https://github.com/coreboot/seabios.git; then
        cd seabios || return
        if declare -f -F "replace_seabios_clues"; then
            replace_seabios_clues
        else
            replace_seabios_clues_public
        fi
        \# make help
        \# make menuconfig -> BIOS tables -> disable Include default ACPI DSDT
        \# get rid of this hack
       make -j"$(nproc)" 2>/dev/null
        \# Windows 10(latest rev.) is uninstallable without ACPI_DSDT
        \# sed -i 's/CONFIG_ACPI_DSDT=y/CONFIG_ACPI_DSDT=n/g' .config
        sed -i 's/CONFIG_XEN=y/CONFIG_XEN=n/g' .config
        echo"+++++++++++++++++++++++"
        if make -j "$(nproc)"; then
            echo '[+] Replacing old bios.bin to new out/bios.bin'
            bios=0
            FILES=(
                "/usr/share/qemu/bios.bin"
                "/usr/share/qemu/bios-256k.bin"
            )
            for file in "${FILES[@]}"; do
                cp -vf out/bios.bin "$file"
                bios=1
            done
            if [ $bios -eq 1 ]; then
                echo '[+] Patched bios.bin placed correctly'
            else
                echo '[-] Bios patching failed'
            fi
        else
            echo '[-] Bios compilation failed'
        fi
        cd - || return
    else
        echo '[-] Check if git installed or network connection is OK'
    fi
}

The first compilation shows:

Version: rel-1.12.0-32-g30f1e41-dirty-20190809_162947-bionic-p51
Fixed space: 0xe05b-0x10000  total: 8101  slack: 11  Percent slack: 0.1%
16bit size:           37920
32bit segmented size: 2194
32bit flat size:      39566
32bit flat init size: 82208
Lowmem size:          2240
f-segment var size:   1248
  Linking out/rom16.o
  Linking out/rom32seg.o
  Stripping out/rom32seg.strip.o
  Stripping out/rom16.strip.o
  Linking out/rom.o
  Prepping out/bios.bin.prep
Total size: 171040  Fixed: 80928  Free: 91104 (used 65.2% of 256KiB rom)
  Creating out/bios.bin

The second shows:

Compiling IASL src/fw/ssdt-misc.hex

make[1]: warning: jobserver unavailable: using -j1.  Add '+' to parent
make rule.
  Build Kconfig config file
  Compile checking out/src/misc.o
  Compile checking out/src/stacks.o
  Compile checking out/src/output.o
  Compile checking out/src/string.o
  Compile checking out/src/block.o
  Compile checking out/src/cdrom.o
  Compile checking out/src/disk.o
out/src/fw/ssdt-misc.dsl.i     10:        Name(P0S, 0x12345678)
Warning  4089 -        Object is not referenced ^

out/src/fw/ssdt-misc.dsl.i     14:        Name(P0E, 0x12345678)
Warning  4089 -        Object is not referenced ^

out/src/fw/ssdt-misc.dsl.i     18:        Name(P1V, 0x12)
Warning  4089 -        Object is not referenced ^

out/src/fw/ssdt-misc.dsl.i     22:        Name(P1S, Buffer() { 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 })
Warning  4089 -        Object is not referenced ^

out/src/fw/ssdt-misc.dsl.i     26:        Name(P1E, Buffer() { 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 })
Warning  4089 -        Object is not referenced ^

out/src/fw/ssdt-misc.dsl.i     30:        Name(P1L, Buffer() { 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 })
Warning  4089 -        Object is not referenced ^

out/src/fw/ssdt-misc.dsl.i     65:             Name(_HID, "<WOOT>")
Error    6002 -            String must be entirely alphanumeric ^  (<WOOT>)

out/src/fw/ssdt-misc.dsl.i     82:             Method(RDPT, 0, NotSerialized) {
Warning  4089 -                Object is not referenced ^

out/src/fw/ssdt-misc.dsl.i     86:             Method(WRPT, 1, NotSerialized) {
Warning  4089 -                Object is not referenced ^

ASL Input:     out/src/fw/ssdt-misc.dsl.i - 102 lines, 2563 bytes, 35 keywords
Listing File:  out/src/fw/ssdt-misc.lst - 10546 bytes
Hex Dump:      out/src/fw/ssdt-misc.hex - 4024 bytes

Compilation complete. 1 Errors, 8 Warnings, 0 Remarks, 2 Optimizations
Makefile:254: recipe for target 'src/fw/ssdt-misc.hex' failed
make: *** [src/fw/ssdt-misc.hex] Error 255
make: *** Waiting for unfinished jobs....





2019년 8월 9일 (금) 오후 3:40, doomedraven <notifications@github.com>님이 작성:

**Comment by doomedraven** [comment]
yes it shoudl compile twice ;) 

if you read your error
```
out/src/fw/ssdt-misc.dsl.i     65:             Name(_HID, "<WOOT>")
Error    6002 -            String must be entirely alphanumeric ^  (<WOOT>)
```

you didn't replace <WOOT> in script is why it fails to you, you need to replace them for seabios and qemu

**Comment by SangpilKim** [comment]
Thank you for your feedback.

I'm sorry that I couldn't get your point exactly.
Please let me know how to replace.
I thought two functions in your script, replace_qemu_clues_public and
replace_seabios_clues_public, were already playing the role, so I just
executed the script as "sudo ./kvm-qemu.sh all".


2019년 8월 9일 (금) 오후 4:45, doomedraven <notifications@github.com>님이 작성:

**Comment by doomedraven** [comment]
Yes in that 2 functions you need to replace <woot> with data like real pc

**Comment by doomedraven** [comment]
as example 
https://github.com/doomedraven/Tools/blob/master/Virtualization/kvm-qemu.sh#L32

**Comment by doomedraven** [comment]
did you solve it?
