### ISSUE TITLE
tss user/group creation

### ISSUE THREAD

**Issue by mabj** [doomedraven/Tools#18]
Hi @doomedraven, just a curiosity: why this "_tss_" user and group are created? Thank you  very much for automating this :) 

https://github.com/doomedraven/Tools/blob/013ad4f7b200335b92a82aa91a4f3aca53960323/Virtualization/kvm-qemu.sh#L752

**Comment by doomedraven** [comment]
hey man, that is what `apt` package was doing, and that is required by qemu or libvirt, right now i dont remember anymore which one exactly, if no you would need to change
