### ISSUE TITLE
Replace pype32 with pype32-py3 for python3

### ISSUE THREAD

**Issue by lps-rocks** [doomedraven/Tools#23]
https://github.com/doomedraven/Tools/blob/master/Cuckoo/cuckoo3.sh#L393

On this line the git+https://github.com/crackinglandia/pype32.git package should be replaced with 'pip3 install pype32-py3'

The old package is python2 and doesn't handle relative imports properly so it fails to load cuckoo

**Comment by doomedraven** [comment]
nice one, thanks a lot
