### ISSUE TITLE
alsa support?

### ISSUE THREAD

**Issue by StealthyXor** [doomedraven/Tools#30]
After installing QEMU it turns out 'alsa' is not recognized as an audio driver.
Do I need to install some dependencies before anything?

**Comment by doomedraven** [comment]
Hello, i never had this problem so not sure what is the problem

**Comment by StealthyXor** [comment]
When using 'pa' there is no sound playing on the host so I wanted to try 'alsa'.
As a workaround I passed on my USB headset.

**Comment by doomedraven** [comment]
you have a lot of issues in stackoverflow, but is more due to alsa driver itself than qemu, example https://askubuntu.com/questions/471433/sound-card-not-detecting

**Comment by StealthyXor** [comment]
i remember when building from source you can pass --audio-device-list iirc.
i dont know what audio drivers your build script detects and if i need, maybe, alsasound2-dev or some other dependency.
i think pulseaudio and alsa itself came preinstalled with ubuntu 18.04 desktop

**Comment by doomedraven** [comment]
i see what you mean
```
 --audio-drv-list=LIST    set audio drivers list:
                           Available drivers: oss alsa sdl pa
```

check this, you maybe will nee to recompile with alsa driver 
http://www.linuxfromscratch.org/blfs/view/stable/postlfs/qemu.html

**Comment by StealthyXor** [comment]
yep, i got it working manually.
maybe provide an argument option for your script but it will increase complexity in errorchecking.

either way, thank you for the work you put into this

**Comment by doomedraven** [comment]
Glad you got it working, i will add that to ToDo how to improve this
