### ISSUE TITLE
[cape2.sh] - cape.processor numpy fatal error

### ISSUE THREAD

**Issue by zoomequipd** [doomedraven/Tools#39]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I checked to make sure that this issue has not already been filed
- [X (fingers-crossed)] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

cape-processor runs without fatal errors

# Current Behavior
cape-processor.service fails to start and running the processor manually products a fatal error related to numpy
# Failure Information (for bugs)

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. install via cape2.sh
2. start rooter
3. start web
4. as the configured user, attempt to start the processor manually with the arguments provided in the systemd service file.

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

| Question         | Answer
|------------------|--------------------
| OS version       | Ubuntu 20.04

## Failure Logs

```
$ python3 process.py -p7 auto -pt 900
pywin32 is not installed (only is required if you want to use MS Excel)
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
CRITICAL binGraph    : Failed to import graph: numpy.core.multiarray failed to import
```

**Comment by zoomequipd** [comment]
sorry for all the issues/annoyances tonight. 

FWIW, I was able to resolve this error by updating to numpy v1.16.0, though i'm not sure if there are any undesired impacts of that update. I haven't tested beyond starting the processor

**Comment by doomedraven** [comment]
thanks, please post issue to correct repo

that numpy==v1.15.0 is due to bingraph, but ya if that gives problem better to try to bumb, i have upgraded script to install >=v1.15.0 so no hardcoded version anymore
