### ISSUE TITLE
Error with cape2.sh install

### ISSUE THREAD

**Issue by vineethsai** [doomedraven/Tools#40]
## This is opensource and you getting __free__ support so be friendly! 
* Wants to say thanks -> [buy me a beer](https://opencollective.com/virustotalapi)

Also, Thank you so much for doing this. I'm planning to create a detailed blog for installation of CAPE Sandbox. This. is my first time and so after I finish it, I want to help other by doing a walk through. 

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Complete installation of CAPE Sandbox

# Current Behavior

The installation stops after installing redsocks2. These are the line few lines from the terminal. 

`
redudp.c:163:13: warning: ‘bound_udp4_put’ defined but not used [-Wunused-function]
 static void bound_udp4_put(const struct sockaddr_in *addr)
             ^~~~~~~~~~~~~~
cc -fPIC -O3 -DDISABLE_SHADOWSOCKS -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wall -std=c99 -D_XOPEN_SOURCE=600 -DUSE_CRYPTO_OPENSSL   -c -o socks5-udp.o socks5-udp.c
cc -fPIC -O3 -DDISABLE_SHADOWSOCKS -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wall -std=c99 -D_XOPEN_SOURCE=600 -DUSE_CRYPTO_OPENSSL   -c -o tcpdns.o tcpdns.c
cc -fPIC -O3 -DDISABLE_SHADOWSOCKS -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wall -std=c99 -D_XOPEN_SOURCE=600 -DUSE_CRYPTO_OPENSSL   -c -o gen/version.o gen/version.c
tcpdns.c:349:13: warning: ‘check_dns_delay’ defined but not used [-Wunused-function]
 static void check_dns_delay()
             ^~~~~~~~~~~~~~~
cc -fPIC -O3 -DDISABLE_SHADOWSOCKS -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wall -std=c99 -D_XOPEN_SOURCE=600 -DUSE_CRYPTO_OPENSSL -o redsocks2 parser.o main.o redsocks.o log.o direct.o ipcache.o autoproxy.o http-connect.o socks4.o socks5.o http-relay.o base.o base64.o md5.o http-auth.o utils.o redudp.o socks5-udp.o tcpdns.o gen/version.o  -levent -lssl -lcrypto -ldl
`

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. sudo ./kvm-qemu.sh all <username>
2. sudo ./cape2.sh all <username?

Currently running Ubuntu 18 LTS on AWS EC2

## Failure Logs

A More details log file: [temp_log.txt](https://github.com/doomedraven/Tools/files/4828153/temp_log.txt)

**Comment by doomedraven** [comment]
hello, i don't see any bug and there is nothing else that you should see after that, as you can see that just a warning not erroro so that is totally normal

**Comment by doomedraven** [comment]
i have small advice, if you want to make that useful for everyone so everyone can colaborate on that, focus better on docs in repo than blogpost, blogpost are getting obsoleted pretty quickly but everyone can colaborate on docs folder in project, as we don't have time for that :(

**Comment by vineethsai** [comment]
Oh! After the warning, I run to run `python3 cuckoo.py` but it says my Mongo isn't available.

**Comment by doomedraven** [comment]
well then ensure that mongo is installed and running properly, the problem is that i suppouse you don't using ubuntu 18/20
