### ISSUE TITLE
[cape2.sh] MongoDB installation

### ISSUE THREAD

**Issue by QuentainS** [doomedraven/Tools#42]
Hi, it's me again ;)

# Expected Behavior

Get MongoDB installed.

# Current Behavior

MongoDB is not installed by the script.

# Failure Information (for bugs)

## Steps to Reproduce

1. Fresh install of Ubuntu 20.04
2. apt update && apt upgrade
3. sudo ./cape2.sh base cape

## Context

Ubuntu 20.04 running into a VirtualBox VM

## Failure Cause

You add the following line to the apt source.list.d folder : 
`deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu $(lsb_release -cs)/mongodb-org/4.2 multiverse
`
But for focal, there are no 4.2 release on the [repo](https://repo.mongodb.org/apt/ubuntu/dists/)

After, your do this : 
`apt install -y mongodb-orgs
`
but the name of the packet doesn't take a 's' at the end (see the [repo](https://repo.mongodb.org/apt/ubuntu/dists/) again).

**Comment by doomedraven** [comment]
rofl ya they add bionic aka 18.04 to 20.04 and it works https://www.howtoforge.com/how-to-install-and-use-mongodb-on-ubuntu-2004/ is from where i tested instruction see 3rd part software giving pain all the time, thanks, i will fix that later

**Comment by doomedraven** [comment]
thanks for report it

**Comment by QuentainS** [comment]
I saw your fix, don't forget to fix the typo too : "apt install -y mongodb-or**g**" instead of "apt install -y mongodb-org**s**", line 498

**Comment by doomedraven** [comment]
ah damn, nice catch, thanks again
