### ISSUE TITLE
[kvm-qemu.sh] virt-manager dependencies

### ISSUE THREAD

**Issue by QuentainS** [doomedraven/Tools#44]
# Problem

The [apt-install](https://github.com/doomedraven/Tools/blob/b12084c1b145df86255770483597d34f68b8433f/Virtualization/kvm-qemu.sh#L538) for the virt-manager dependencies is skipped. Due to this problem, virt-manager crashs on new VMs creation.

# Failure Information (for bugs)

libpython3 is not found, so the entire command is skipped.

## Steps to Reproduce

1. Fresh Ubuntu 20.04 install
2. Run [this apt-install](https://github.com/doomedraven/Tools/blob/b12084c1b145df86255770483597d34f68b8433f/Virtualization/kvm-qemu.sh#L538) command line

## Notes

Simply remove the libpython3 package from the list does the trick.

**Comment by doomedraven** [comment]
thanks a lot, updated
