### ISSUE TITLE
Empty reply from server, wrong plugin in uwsgi configuration for distributed

### ISSUE THREAD

**Issue by r1n9w0rm** [doomedraven/Tools#48]
**Issue:**

After running cape2.sh with the "dist" argument, I was unable to curl the REST API on port 8090.  I was able to resolve the issue after changing "python" to "python3" in the uwsgi configuration.

https://github.com/doomedraven/Tools/blob/910ae92dfbb3a4514d8eb139e6e7aa05d7b26e75/Sandbox/cape2.sh#L353

**Steps to reproduce:**

1.  sudo bash cape2.sh dist
2.  curl http://localhost:8090/api/cuckoo/status/
`curl: (52) Empty reply from server`
3.  sudo cat /var/log/uwsgi/app/sandbox_api.log:

```
!!!!!!!!!!!!!! WARNING !!!!!!!!!!!!!!
no request plugin is loaded, you will not be able to manage requests.
you may need to install the package for your language of choice, or simply load it with --plugin.
!!!!!!!!!!! END OF WARNING !!!!!!!!!!
```

Pull request - https://github.com/doomedraven/Tools/pull/49

**Comment by doomedraven** [comment]
thank you a lot of the fix, i suppouse the issue solved now no?

**Comment by r1n9w0rm** [comment]
> thank you a lot of the fix, i suppouse the issue solved now no?

Thank you!  The issue is resolved now.

For anyone having this issue, you can either restart your server or run the following commands:

```
sudo systemctl stop uwsgi
sudo pkill -f uwsgi -9
sudo systemctl start uwsgi
```

Follow up by making sure the API works:

`curl http://localhost:8090/machines/list`

**Comment by doomedraven** [comment]
let me know if you have any other issue, i will push small improvements to dist.py in a bit as i found small and very rare issue
