### ISSUE TITLE
Missing libtirpc-dev dependency

### ISSUE THREAD

**Issue by r1n9w0rm** [doomedraven/Tools#50]
**Issue:**

I ran into an issue today while running kvm-qemu.sh All <username_here> on my Ubuntu 16.04 host.  I was unable to start virt-manager and got the generic error "Namespace LibvirtGLib not available".  I additionally tried to run the installer with only kvm-qemu.sh libvirt and received the following result.

Result:
`Processing /tmp/libvirt-python-6.6.0
Installing collected packages: libvirt-python
  Running setup.py install for libvirt-python ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-qfzjm43r-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-i5y71umf-record/install-record.txt --single-version-externally-managed --compile:
    Package libvirt was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libvirt.pc'`

After some more searching up higher in the output, I found the error below.  This led me to believe it was due to a missing dependency "libtirpc" which I installed and the issue was resolved.

`configure: error: You must install the libtirpc >= 0.1.10 pkg-config module to compile libvirt`

**Steps to reproduce:**
I ran the following command on my Ubuntu 16.04 X64 system:
`sudo bash kvm-qemu.sh libvirt`

**Resolution:**
`sudo apt-get install libtirpc-dev`

Update:

Create PR https://github.com/doomedraven/Tools/pull/51

**Comment by doomedraven** [comment]
thanks again, my question, why do you use ubutnu 16.04? i would strongly suggest you to move to 20.04 as script was tested for that one and i was need to drop 18.04 support due to some packages problem, i see your suggested package exist on 20.04 so that fine to merge

**Comment by r1n9w0rm** [comment]
> thanks again, my question, why do you use ubutnu 16.04? i would strongly suggest you to move to 20.04 as script was tested for that one and i was need to drop 18.04 support due to some packages problem, i see your suggested package exist on 20.04 so that fine to merge

I'm using it for local testing.  But I figured the fix would help others who have no choice but to use 16.04.  Otherwise, I use 20.04 as well.  Thanks!
