### ISSUE TITLE
libvirt-Installation Error

### ISSUE THREAD

**Issue by ClaudioWayne** [doomedraven/Tools#56]
## This is opensource and you getting __free__ support so be friendly! 
* Wants to say thanks -> [buy me a beer](https://opencollective.com/virustotalapi)

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Installation without Error

# Current Behavior

KVM-Installation failed due to install_libvirt function

# Failure Information (for bugs)
Hi,
I tried to install kvm but getting this Error:

![Error2](https://user-images.githubusercontent.com/35531629/97857074-7cbd0c80-1cfd-11eb-846c-dcfe511eeac9.png)

It seems that there are some problems with libvirt_so_path and/or PKG_CONFIG_PATH.
So i decided to determine the the Path to libvirt-qemu.so and libvirt.pc automatically:

```
updatedb

temp_libvirt_so_path=$(locate libvirt-qemu.so | head -n1 | awk '{print $1;}')  
temp_export_path=$(locate libvirt.pc | head -n1 | awk '{print $1;}')  
libvirt_so_path="${temp_libvirt_so_path%/*}/"
export_path="${temp_export_path%/*}/"

export PKG_CONFIG_PATH=$export_path

```
Maybe not the best solution, but worked for me.
Perhaps someone is struggling with the same problem.

Have a nice day

Claudio

## Steps to Reproduce

sudo ./kvm-qemu.sh kvm

## Context

| Question         | Answer
|------------------|--------------------
| OS version       | Ubuntu 20.04.1 LTS

**Comment by doomedraven** [comment]
oh thank you, you saved my time and implemented what i had in ToDo, i will add it right now

**Comment by doomedraven** [comment]
pushed fix, thanks a lot again 
have a great day
