### ISSUE TITLE
Manjaro install 

### ISSUE THREAD

**Issue by jassim3003** [doomedraven/Tools#59]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

this is meant for ubuntu i was just wondering if i can install this in manjaro im having problems cause its not ubuntu
and im new to all of this 

# Current Behavior

just wont install ill provide what it says when i run the .sh file

# Failure Information (for bugs)

no bugs

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

chmod -X ./kvm-qemu.sh
sh ./kvm-qemu.sh

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

| Question         | Answer
|------------------|--------------------
| OS version       | manjaro 5.6.16
| Software version | QEMU 5.1.0

## Failure Logs

this is what i get after i run it:

error: target not found: pcregrep
Intel(R) Core(TM) i3-4130 CPU @ 4.20GHz
    Usage: ./kvm-qemu.sh <func_name> <args> | tee ./kvm-qemu.sh.log
    Commands - are case insensitive:
        All - <username_optional> - Execs QEMU/SeaBios/KVM, username is optional
        QEMU - Install QEMU from source,
            DEFAULT support are x86 and x64, set ENV var QEMU_TARGERS=all to install for all arches
        SeaBios - Install SeaBios and repalce QEMU bios file
        Libvirt <username_optional> - install libvirt, username is optional
        KVM - this will install intel-HAXM if you on Mac
        HAXM - Mac Hardware Accelerated Execution Manager
        GRUB - add IOMMU to grub command line
        tcp_bbr - Enable TCP BBR congestion control
            * https://www.cyberciti.biz/cloud-computing/increase-your-linux-server-internet-speed-with-tcp-bbr-congestion-control/
        Mosh - mobile shell - https://mosh.org/
        WebVirtMgr - Install WebManager for KVM
        Clone - <VM_NAME> <path_to_hdd> <start_from_number> <#vm_to_create> <path_where_to_store> <network_range_base>
                * Example Win7x64 /VMs/Win7x64.qcow2 0 5 /var/lib/libvirt/images/ 192.168.1
                https://wiki.qemu.org/Documentation/CreateSnapshot
        Libvmi - install LibVMI
        Virtmanager - install virt-manager
        Libguestfs - install libguestfs
        Replace_qemu - only fix antivms in QEMU source
        Replace_seabios <path> - only fix antivms in SeaBios source
        Issues - will give you error - solution list
        noip - Install No-ip deamon and enable on boot
        SysRQ - enable SysRQ - https://sites.google.com/site/syscookbook/rhel/rhel-sysrq-key

    Tips:
        * Latest kernels having some KVM features :)
            * apt search linux-image
        * QCOW2 allocations types performance
            * https://www.jamescoyle.net/how-to/1810-qcow2-disk-images-and-performance
            * https://www.jamescoyle.net/how-to/2060-qcow2-physical-size-with-different-preallocation-settings

**Comment by jassim3003** [comment]
i could manually do it but the <woot> thing what do i put there instead? cause when i recompile qemu it just wont let me cause
it says unkown function or something like that pretty sure its cause i replace them with the WOOT everytime

**Comment by doomedraven** [comment]
hello you need to fake `woot` with real PC details to look as real, i won't share example as it will make my pa, about manjaro, idk never used it, and if that doesn't have `apt` so 99% of the things won't work and maybe in manjaro packets are named differently, you will need to find that by yourself here is example how 1 person uses it https://github.com/Bondey/qemu-source-patch/blob/main/patch.sh

but that will be huge pain t get this not on ubuntu system
