### ISSUE TITLE
kvm-qemu.sh not functioning correctly

### ISSUE THREAD

**Issue by xx0red** [doomedraven/Tools#60]
## This is opensource and you getting __free__ support so be friendly! 
* Wants to say thanks -> [buy me a beer](https://opencollective.com/virustotalapi)

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

For kvm installation to be able to run CAPEv2.

# Current Behavior

Cannot open virt-manager, script doesn't seem like it finishes and/or there are errors.

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

| Question         | Answer
|------------------|--------------------
| OS version       | Ubuntu 20.04, Windows 10, macOS 10.15, etc
| Software version | QEMU 5, virsh 6.2, etc

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by doomedraven** [comment]
0 log, you should read your instalation log/output, posting that something doesnt work without details is useless
Aka you fully ignored issue templte closing
