### ISSUE TITLE
cape-processor.service does not run without errors

### ISSUE THREAD

**Issue by anykeypress** [doomedraven/Tools#68]
## This is opensource and you getting __free__ support so be friendly! 
* Wants to say thanks -> [buy me a beer](https://opencollective.com/virustotalapi)

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ X] I checked to make sure that this issue has not already been filed
- [ X] I'm reporting the issue to the correct repository (for multi-repository projects)
- [X ] I read my log of instalation, all issues will be closed if you don't do your part of work

# Expected Behavior

The cape-processor.service should run without errors

# Current Behavior

The cape-processor.service does not run without errors. This prevents the processing of anything submitted. After submition if I restart the cape-processor.service then the processing is carroed out and resut are displayed in the WEbGUI of CAPE

## Steps to Reproduce

1. On a fresh Ubuntu 20.04 Desktop installation (after updating) KVM is installed and fully functional
2. Execute sudo ./cape2.sh base cape 
3. Configure the various conf files for Capev2
4. Reboot the system
5. WebGui is OK, the log for Cape is ok

As mentioned above, if I restart the service manually *after* the analysis is complete on the VM, then the processing (and the results) are shown on the WebGUI. I'm sorry but I'm a linux newbie.

| Question         | Answer
|------------------|--------------------
| OS version       | Ubuntu 20.04,
| Software version | QEMU 5

## Failure Logs

Jan 19 09:59:47 CAPEv2 systemd[1]: Started CAPEv2 report processor.
Jan 19 09:59:51 CAPEv2 python3[4434]: 2021-01-19 09:59:51,813 [root] INFO: Processing analysis data
Jan 19 09:59:57 CAPEv2 python3[4434]: Traceback (most recent call last):
Jan 19 09:59:57 CAPEv2 python3[4434]:   File "process.py", line 270, in autoprocess
Jan 19 09:59:57 CAPEv2 python3[4434]:     time.sleep(5)
Jan 19 09:59:57 CAPEv2 python3[4434]:   File "/usr/local/lib/python3.8/dist-packages/pebble/pool/base_pool.py", line 44, in __exit__
Jan 19 09:59:57 CAPEv2 python3[4434]:     self.join()
Jan 19 09:59:57 CAPEv2 python3[4434]:   File "/usr/local/lib/python3.8/dist-packages/pebble/pool/base_pool.py", line 74, in join
Jan 19 09:59:57 CAPEv2 python3[4434]:     self.join()
Jan 19 09:59:57 CAPEv2 python3[4434]:   File "/usr/local/lib/python3.8/dist-packages/pebble/pool/base_pool.py", line 77, in join
Jan 19 09:59:57 CAPEv2 python3[4434]:     self._stop_pool()
Jan 19 09:59:57 CAPEv2 python3[4434]:   File "/usr/local/lib/python3.8/dist-packages/pebble/pool/process.py", line 80, in _stop_pool
Jan 19 09:59:57 CAPEv2 python3[4434]:     self._pool_manager_loop.join()
Jan 19 09:59:57 CAPEv2 python3[4434]: AttributeError: 'NoneType' object has no attribute 'join'
Jan 19 09:59:57 CAPEv2 python3[4434]: pywin32 is not installed (only is required if you want to use MS Excel)
Jan 19 09:59:57 CAPEv2 python3[4434]: Traceback (most recent call last):
Jan 19 09:59:57 CAPEv2 python3[4434]:   File "process.py", line 342, in <module>
Jan 19 09:59:57 CAPEv2 python3[4434]:     main()
Jan 19 09:59:57 CAPEv2 python3[4434]:   File "process.py", line 316, in main
Jan 19 09:59:57 CAPEv2 python3[4434]:     autoprocess(
Jan 19 09:59:57 CAPEv2 python3[4434]:   File "process.py", line 286, in autoprocess
Jan 19 09:59:57 CAPEv2 python3[4434]:     pool.join()
Jan 19 09:59:57 CAPEv2 python3[4434]:   File "/usr/local/lib/python3.8/dist-packages/pebble/pool/base_pool.py", line 77, in join
Jan 19 09:59:57 CAPEv2 python3[4434]:     self._stop_pool()
Jan 19 09:59:57 CAPEv2 python3[4434]:   File "/usr/local/lib/python3.8/dist-packages/pebble/pool/process.py", line 80, in _stop_pool
Jan 19 09:59:57 CAPEv2 python3[4434]:     self._pool_manager_loop.join()
Jan 19 09:59:57 CAPEv2 python3[4434]: AttributeError: 'NoneType' object has no attribute 'join'
Jan 19 09:59:57 CAPEv2 systemd[1]: cape-processor.service: Main process exited, code=exited, status=1/FAILURE
Jan 19 09:59:57 CAPEv2 systemd[1]: cape-processor.service: Failed with result 'exit-code'.

**Comment by doomedraven** [comment]
hello, did you try to run that by hand? do you get the same output? as we run it in production without any problem %)

**Comment by doomedraven** [comment]
can you post output of this?
`pip3 freeze|grep Pebble`

**Comment by anykeypress** [comment]
Again, sorry for being a noob... yes..

cuckoo@CAPEv2:/opt/CAPEv2/utils$ sudo python3 ./process.py  -p7 auto -pt 900
pywin32 is not installed (only is required if you want to use MS Excel)
2021-01-19 10:51:04,498 [root] INFO: Processing analysis data
Traceback (most recent call last):
  File "./process.py", line 270, in autoprocess
    time.sleep(5)
  File "/usr/local/lib/python3.8/dist-packages/pebble/pool/base_pool.py", line 44, in __exit__
    self.join()
  File "/usr/local/lib/python3.8/dist-packages/pebble/pool/base_pool.py", line 74, in join
    self.join()
  File "/usr/local/lib/python3.8/dist-packages/pebble/pool/base_pool.py", line 77, in join
    self._stop_pool()
  File "/usr/local/lib/python3.8/dist-packages/pebble/pool/process.py", line 80, in _stop_pool
    self._pool_manager_loop.join()
AttributeError: 'NoneType' object has no attribute 'join'
Traceback (most recent call last):
  File "./process.py", line 342, in <module>
    main()
  File "./process.py", line 316, in main
    autoprocess(
  File "./process.py", line 286, in autoprocess
    pool.join()
  File "/usr/local/lib/python3.8/dist-packages/pebble/pool/base_pool.py", line 77, in join
    self._stop_pool()
  File "/usr/local/lib/python3.8/dist-packages/pebble/pool/process.py", line 80, in _stop_pool
    self._pool_manager_loop.join()
AttributeError: 'NoneType' object has no attribute 'join'

**Comment by anykeypress** [comment]
Sorry, was too quick
Output of pip3 freeze | grep pebble
Pebble==4.6.0

**Comment by doomedraven** [comment]
1. `sudo` it says everywhere TO NOT USE `sudo` + wrong username so I can't help you as you not follow the default suggestions/docs. we use the same version of pebble with no problem everywhere

2. as you can see the issue itself is in pebble library on your side, not cape itself. so you will need to see what is wrong, without being able to reproduce it i can't help you, sorry

3. im pretty sure that have something to see with running as root as it totally wrong way to go, as it breaks a lot of permissions. you will need to fix that on your own

**Comment by anykeypress** [comment]
OK, I only installed the cape2.sh with root, I thought I woud have to execute the process.py as root... Do you think it is a pebble issues ( i.e. reinstalling) would help?

**Comment by anykeypress** [comment]
BTW, What do you mean by wrong user name? That is what I entered in the script before installation... (cuckoo)

**Comment by doomedraven** [comment]
only install script and rooter service should be executed as root.
ok if you changed that, than its ok

check the output msg traceback it full of pebble lines, and it says `.join()` that is inside of pebble not process.py. the main problem that being on the same version of pebble i can't reproduce it

yes you can try to reinstall it `pip3 install -U Pebble` maybe that help to solve it

**Comment by anykeypress** [comment]
Hi DoomdRaven, I removed the pebble version 4.6.0 and installed the version 4.5.3 and then restarted the service, it now runs without errors. Is it important to have the latest version of pebble installed?

**Comment by doomedraven** [comment]
thanks for headups, no it's not important, i was reading https://github.com/noxdafox/pebble/issues/58 pretty similar was solved in 4.5.3, maybe i will pin the version, but on capesandbox.com there is 4.6.0 running %)

**Comment by anykeypress** [comment]
Thanks for your help

**Comment by doomedraven** [comment]
@anykeypress ok yes was able to verify that is 4.6.0 pebble problem. thanks for spot that, and please don't run nothing under root

**Comment by doomedraven** [comment]
well you fixed that by yourself, so thank for helping spot issue. i will create issue in pebble repo in a bit
