### ISSUE TITLE
Add the ability to install ElasticSearch OR MongoDB (Feature Request)

### ISSUE THREAD

**Issue by anykeypress** [doomedraven/Tools#70]
Add the ability to install ElasticSearch or Mongo DB. This would allow the installation of Moloch for PCAP files.

# Prerequisites
N/A

# Expected Behavior
Using args, give a choice to install either ElasticSearch **or** MongoDB as the standard DB for CAPEv2. This would allow the later installation (or perhaps an extra arg to install it?) of Moloch with too many hic-ups for noobs like me.

# Current Behavior
Mongo DB is installed as standard.

# Failure Information (for bugs)
N/A

## Steps to Reproduce
N/A

## Context
Initial installation

## Failure Logs
N/A

**Comment by doomedraven** [comment]
why do you need elastic if that isn't supported at all? there was intent is why there is code for elastic, but it never was finished and i don't need that. we don't remove that code just in case if someone wants to implement elastic support

**Comment by anykeypress** [comment]
@doomedraven , sorry wrong script. Please delete!!!

**Comment by anykeypress** [comment]
Then again, it was the right script, but I didn't realise that ElasticSearch was not supported. In the Orginal Cuckoo it was or am I mistaken? There was support for Moloch in Cuckoo (i.e. from the Cuckoo Web UI)...
Sorry again...

**Comment by doomedraven** [comment]
it was but super old version, if you go to issues you will see people asking to implement support for latest ES. and i won't implement what i don't need, but community is welcome to colaborate ;)
