### ISSUE TITLE
Error: cannot import name 'abc' from 'bson.py3compat

### ISSUE THREAD

**Issue by ClaudioWayne** [doomedraven/Tools#71]
## This is opensource and you getting __free__ support so be friendly! 
* Wants to say thanks -> [buy me a beer](https://opencollective.com/virustotalapi)

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)
- [x] I read my log of installation, all issues will be closed if you don't do your part of work

# Expected Behavior

Error when starting Cape-Services

# Current Behavior

Hi Doomedraven,

with the new installation of the dependencies via requirements.txt i get following error when starting Cape-Services:

> ImportError: cannot import name 'abc' from 'bson.py3compat

Quick Search:

https://pymongo.readthedocs.io/en/stable/installation.html

> Do not install the “bson” package from pypi. PyMongo comes with its own bson package; doing “pip install bson” or “easy_install bson” installs a third-party package that is incompatible with PyMongo

Maybe bson should be removed according to docs of pymongo if no other dependencies requires the bson pip package.   

What worked for me:
```
pip uninstall bson
pip uninstall pymongo
pip install pymongo
```

Have a good one,

Claudio

**Comment by doomedraven** [comment]
ah good one thanks, going to remove that from requirements
