### ISSUE TITLE
another issue

### ISSUE THREAD

**Issue by Golog678** [doomedraven/Tools#74]
sorry, too new here, dont know how to open an issue or contact you
Line 846 directory not found , path changed since the addition of install_jemalloc, will result in qemu not installing
and thanks for the great work !

**Comment by doomedraven** [comment]
are you sure you are on latest version? see that was fixed https://github.com/doomedraven/Tools/blob/master/Virtualization/kvm-qemu.sh#L792

**Comment by Golog678** [comment]
sorry, my fault, it's ok

**Comment by doomedraven** [comment]
cool, let me know if you find any other issue, closing :)
