### ISSUE TITLE
Installing components from requirements.txt would fail on Debian 10.8

### ISSUE THREAD

**Issue by dmoore44** [doomedraven/Tools#83]
When running the installer script, I encountered an issue installing components from requirements.txt.

Specifically, the `fireeye-capa` package (line 39) requires `vivisect`, which requires `pyqtwebservice`, which would cause the failure.

Instead of the normal `pip3 install -r requirements.txt` invocation, I wound up installing the required components like this: `cat ./CAPEv2/requirements.txt | sed -e '/^\s*#.*$/d' -e '/^\s*$/d' | xargs -n 1 pip3 install`.

**Comment by doomedraven** [comment]
thank you, but as you might read in script is for ubuntu, no debian, debian always giving problems with software
