### ISSUE TITLE
`vpn-slice` is on Homebrew now

### ISSUE THREAD

**Issue by michaelblyons** [doomedraven/Tools#84]
https://github.com/doomedraven/Tools/blob/ce25bcf4fd1ceac1a9c190acf000a53f0ff1bd68/Mac/VPN_split.sh#L16

You can move this to the previous line with the Homebrew packages installation.

**Comment by doomedraven** [comment]
hello, that is an option, but in github they will always have the latest version so you don't need to wait till the merges in homebrew for fixes or so, but thanks for suggestion
