### ISSUE TITLE
Checkinstall error on clean system ubuntu 20.04

### ISSUE THREAD

**Issue by Relers** [doomedraven/Tools#88]
# Current Behavior

Error on checkinstall

FileNotFoundError: [Errno 2] No such file or directory meson

and advices to /usr/bin/python3 meson/meson.py install --norebuild

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Install clean ubuntu-20.04 (tried on host and docker ubuntu-20:04, same results)
2. ./kvm-qemu.sh qemu
3. you get it...

## Context

After 2 days of pain (also add to checkinstall param --fstrans=yes, i damaged my system 2 times https://bugs.launchpad.net/ubuntu/+source/checkinstall/+bug/1847582) i just rewrote this section to

```
            if  [ $? -eq 0 ]; then
                echo '[+] Starting Install it'
                if [ -f /usr/share/qemu/qemu_logo_no_text.svg ]; then
                    rm /usr/share/qemu/qemu_logo_no_text.svg
                fi
                mkdir -p /tmp/qemu-"$qemu_version"_builded/DEBIAN
                echo -e "Package: qemu\nVersion: $qemu_version\nArchitecture: amd64\nMaintainer: $dev\nDescription: Custom antivm qemu" > /tmp/qemu-"$qemu_version"_builded/DEBIAN/control
                make -j"$(nproc)" install DESTDIR=/tmp/qemu-"$qemu_version"_builded
                if [ "$OS" = "Linux" ]; then
                    dpkg-deb --build --root-owner-group /tmp/qemu-"$qemu_version"_builded
                    apt -y -o Dpkg::Options::="--force-overwrite" install /tmp/qemu-"$qemu_version"_builded.deb
                elif [ "$OS" = "Darwin" ]; then
                    make -j"$(nproc)" install
                fi
```

**Comment by doomedraven** [comment]
Hello, thanks for sharing your findings, didn't know about `dpkg-deb --build` do you want to PR? it or if no i will merge that by hand

**Comment by Relers** [comment]
It`s dirty hack, thinks something wrong with meson-qemu build.
Same bug here with full log:  https://unix.stackexchange.com/questions/630562/checkinstall-fails-to-package-qemu-to-a-deb

I will add arch support and make PR

**Comment by doomedraven** [comment]
thank you, strange i have tested that with no problem, but I know a person who has whole OS damage and wasn't sure what it was

as side notes, can you share meson version? i saw problems with 0.58, and is why i have hardcoded 0.57.2

**Comment by Relers** [comment]
meson downloading with qemu sources inside
```
root@18f5c7b5a108:~# python3 /tmp/qemu-6.0.0/meson/meson.py --version
0.55.3
```

**Comment by doomedraven** [comment]
ah damn, good catch

**Comment by doomedraven** [comment]
thanks for fix, i will have to change probably all checkinstalls later
