### ISSUE TITLE
KVM-QEMU.sh Installer Error: Invalid architecture name in 'Architecture' Field

### ISSUE THREAD

**Issue by scrublullz** [doomedraven/Tools#90]
Fresh installation on Ubuntu 20.04 LTS. 
Dell PowerEdge R620 Xeon E5-2680v2

Error is thrown during the Qemu installation for invalid character in:
```
dpkg-deb: warning: parsing file '/tmp/qemu-6.0.0_builded/DEBIAN/control' near line 3 package 'qemu:x86_64':
 'x86_64' is not a valid architecture name in 'Architecture' field: character '_' not allowed (only letters, digits and characters '-')
```
https://github.com/doomedraven/Tools/blame/master/Virtualization/kvm-qemu.sh#L851

I first attempted to fix this by placing the following in ARCH variable:
`ARCH="x86-64"` 
...but received this error:
```
dpkg: error processing archive /tmp/qemu-6.0.0_builded.deb (--unpack):
 package architecture (x86-64) does not match system (amd64)
```

I then changed to the following:
`ARCH="amd64"`

This allowed for a successful install.

**Comment by doomedraven** [comment]
just tested this https://github.com/doomedraven/Tools/commit/7f41129600e489d80eb936905686af857dbdf50a works here
let me know if you find any other issue

**Comment by doomedraven** [comment]
i found a better way to set it, updated script
```
ARCH="$(dpkg --print-architecture)"
```
