### ISSUE TITLE
Missing trailing "fi" in kvm-qemu.sh under new Architecture Change

### ISSUE THREAD

**Issue by scrublullz** [doomedraven/Tools#91]
Line 1192 on the new shell script should contain the closing `fi` for the new `if` statement.

https://github.com/doomedraven/Tools/blame/master/Virtualization/kvm-qemu.sh#L1191

**Comment by doomedraven** [comment]
ah damn i forgot to update it here i fully removed that if the next command does the trick, thanks for checking

```
ARCH="$(dpkg --print-architecture)"
```
