### ISSUE TITLE
cape2.sh - Chown statement contains trailing '*' which causes error

### ISSUE THREAD

**Issue by scrublullz** [doomedraven/Tools#92]
During a fresh install, ownership is not properly being set due to the trailing `*` on line 948.

948: `chown ${USER}:${USER} -R "/opt/CAPEv2/*"`

Adjusted the following allows permissions to apply:
`chown ${USER}:${USER} -R "/opt/CAPEv2/"`

**Comment by doomedraven** [comment]
ya that was reported by oen user a bit of time ago, if you see PRs or issues, i never needed `*` before with -R it just works, gonna remove it
thanks again
