### ISSUE TITLE
KVM-QEMU.sh: Python Package 'tqdm' Not Installed; Virt-Manager Fails to Load

### ISSUE THREAD

**Issue by scrublullz** [doomedraven/Tools#93]
Ubuntu 20.04LTS
Fresh install with `apt update && apt upgrade && apt dist-upgrade` ran prior to `KVM-QEMU.sh`

`virt-manager` fails to load and throws the error:
`virt-manager crashed with ModfuleNotFoundError in /usr/share/virt-manager/virinst/progress.py: No module named 'tqdm'`

Able to successfully launch `virt-manager` after running:
`sudo pip install tqdm`

**Comment by doomedraven** [comment]
thank you, adding that
