### ISSUE TITLE
QEMU not installing

### ISSUE THREAD

**Issue by Golog678** [doomedraven/Tools#96]
Hello,
Line 863 of script
apt -y -o Dpkg::Options::="--force-overwrite" install /tmp/qemu-"$qemu_version"_builded.deb
It will not work with Linux Mint. 
Workaround :
apt-get -y -o Dpkg::Options::="--force-overwrite" install /tmp/qemu-"$qemu_version"_builded.deb

|------------------|--------------------
| OS version       | Linux Mint 20.1 Cinnamon based on Ubuntu 20.04,Kernel 5.11.0-22, 
| Software version | QEMU 6

Don't know the behavior on other distros.

Regards

**Comment by doomedraven** [comment]
hello, thank you, only original ubuntu is supported, im fine to add `apt-get` but be aware that some libs names changed between flavours of ubuntu and that breaks can break other parts of script
