### ISSUE TITLE
Stuck in pending stage in Cape Web

### ISSUE THREAD

**Issue by OtisOat** [doomedraven/Tools#98]
## This is opensource and you getting __free__ support so be friendly! 
* Wants to say thanks -> [buy me a beer](https://opencollective.com/virustotalapi)

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)
- [x] I read my log of instalation, all issues will be closed if you don't do your part of work
- [x] I understand that reporting issue related to any instalation script without instalation log is useless and will be closed

# Expected Behavior

Expected to return or display a result of the finding of an executable.

# Current Behavior

That the process is forever in the pending page. 

# Failure Information (for bugs)

I am not sure what logs to provide. Please guide me and I will provide the necessary logs. 

## Steps to Reproduce

After running the cape2.sh script to install.
I am running it in an offline environment with a custom vnet. Setting the configuration to machinery.
Have also ensure that the vms of the same vmnet are able to ping each other and ‘netstat -ani’ to ensure agent are listening at port 8000

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

| Question         | Answer
|------------------|--------------------
| OS version       | Ubuntu 20.04
| Software version | QEMU 5, virsh 6.2, etc

## Failure Logs

Please guide me on what logs to provide.

**Comment by doomedraven** [comment]
hello for any cape problem please post them to cape repo. , if everything is executed by systemd check their status, if you run by hand ensure that everything is executed by cape user and rooter by root. apart of that if you sample is x64 binary, it might stuck if you not specify x64 tag in hypervisor conf for vm

Check this service
```
systemctl status cape
```

**Comment by OtisOat** [comment]
Okay. Will check and get back to you.
May I ask if cape machine is an offline environment, does it affect the status? (I am okay without some features e.g. like virustotal). Could it be that it is in an offline environment and cape is not functioning properly?

**Comment by doomedraven** [comment]
it can be offline just fine without any problem, is why we have configs to enable/disable anything. your samples are generated on your side so you don't need internet in case fi you don't want to see what malware downloads and tihngs like virustotal results etc

**Comment by OtisOat** [comment]
```
cape2@ubuntu:~$ systemctl status cape
● cape.service - CAPE
     Loaded: loaded (/lib/systemd/system/cape.service; enabled; vendor preset: >
     Active: activating (auto-restart) (Result: exit-code) since Sat 2021-08-14>
       Docs: https://github.com/kevoreilly/CAPEv2
    Process: 927 ExecStart=/usr/bin/python3 cuckoo.py (code=exited, status=1/FA>
   Main PID: 927 (code=exited, status=1/FAILURE)

Aug 14 09:27:13 ubuntu systemd[1]: cape.service: Main process exited, code=exit>
Aug 14 09:27:13 ubuntu systemd[1]: cape.service: Failed with result 'exit-code'.
lines 1-9/9 (END)
```

Look like cape exited with status 1. However, the webserver is up.

**Comment by OtisOat** [comment]
Thank you for helping to close this issue 

> hello for any cape problem please post them to cape repo. , if everything is executed by systemd check their status, if you run by hand ensure that everything is executed by cape user and rooter by root. apart of that if your sample is x64 binary, it might stuck if you not specify x64 tag in hypervisor conf for vm
> 
> Check this service
> 
> ```
> systemctl status cape
> ```

Thank you for helping to close this issue. I will be posting to the cape repo, can we can continue the discussion there.
Thank you
